services:
  - type: web
    name: OABS
    env: docker
    plan: free
    rootDir: OABS             # Your app still lives in /OABS
    dockerfilePath: ./Dockerfile  #  Dockerfile is now in root
    envVars:
      - key: DB_HOST
        value: your-mysql-host
      - key: DB_USER
        value: your-db-username
      - key: DB_PASS
        value: your-db-password
      - key: DB_NAME
        value: oabs
      - key: SMTP_USER
        value: your-smtp-user
      - key: SMTP_PASS
        value: your-smtp-password
