services:
  - type: web
    name: oabs-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: your-mysql-host
      - key: DB_USER
        value: your-mysql-username
      - key: DB_PASS
        value: your-db-password
      - key: DB_NAME
        value: oabs
      - key: SMTP_USER
        value: your-smtp-user
      - key: SMTP_PASS
        value: your-smtp-password
